package com.ycandyz.master.enums;

public enum ExpressEnum {

    YUANTONG("yuantong", "圆通速递"),
    YUNDA("yunda", "韵达快递"),
    YOUZHENGGUONEI("youzhengguonei", "邮政快递包裹"),
    SHENTONG("shentong", "申通快递"),
    SHUNFENG("shunfeng", "顺丰速运"),
    ZHONGTONG("zhongtong", "中通快递"),
    HUITONGKUAIDI("huitongkuaidi", "百世快递"),
    JD("jd", "京东物流"),
    TIANTIAN("tiantian", "天天快递"),
    EMS("ems", "EMS"),
    JTEXPRESS("jtexpress", "极兔速递"),
    YOUZHENGBK("youzhengbk", "邮政标准快递"),
    ZHAIJISONG("zhaijisong", "宅急送"),
    DEBANGWULIU("debangwuliu", "德邦"),
    DEBANGKUAIDI("debangkuaidi", "德邦快递"),
    ZHONGTONGKUAIYUN("zhongtongkuaiyun", "中通快运"),
    BAISHIWULIU("baishiwuliu", "百世快运"),
    YOUSHUWULIU("youshuwuliu", "优速快递"),
    YUNDAKUAIYUN("yundakuaiyun", "韵达快运"),
    ANNENGWULIU("annengwuliu", "安能快运"),
    ZHONGYOUEX("zhongyouex", "众邮快递"),
    YUANTONGKUAIYUN("yuantongkuaiyun", "圆通快运"),
    ZHONGTONGGUOJI("zhongtongguoji", "中通国际"),
    SUNING("suning", "苏宁物流"),
    NSF("nsf", "新顺丰（NSF）"),
    YOUZHENGGUOJI("youzhengguoji", "国际包裹"),
    UPSEN("upsen", "UPS-全球件"),
    SUER("suer", "速尔快递"),
    KUAYUE("kuayue", "跨越速运"),
    DHLEN("dhlen", "DHL-全球件"),
    FEDEX("fedex", "FedEx-国际件"),
    ANNTO("annto", "安得物流"),
    EMSGUOJI("emsguoji", "EMS-国际件"),
    DHL("dhl", "DHL-中国件"),
    ZTKY("ztky", "中铁快运"),
    LNTJS("lntjs", "特急送"),
    YIMIDIDA("yimidida", "壹米滴答"),
    DANNIAO("danniao", "丹鸟"),
    EWE("ewe", "EWE全球快递"),
    USPS("usps", "USPS"),
    LIANHAOWULIU("lianhaowuliu", "联昊通"),
    SUBIDA("subida", "速必达"),
    RRS("rrs", "日日顺物流"),
    SHPOST("shpost", "同城快寄"),
    JIUYESCM("jiuyescm", "九曳供应链"),
    UPS("ups", "UPS"),
    EMSBG("emsbg", "EMS包裹"),
    LIANBANGKUAIDI("lianbangkuaidi", "联邦快递"),
    XINFENGWULIU("xinfengwuliu", "信丰物流"),
    ZHONGYOUWULIU("zhongyouwuliu", "中邮物流"),
    ZHUANYUNSIFANG("zhuanyunsifang", "转运四方"),
    AUEXPRESS("auexpress", "澳邮中国快运"),
    JINGUANGSUDIKUAIJIAN("jinguangsudikuaijian", "京广速递"),
    BTEXPRESS("btexpress", "邦泰快运"),
    SXJDFREIGHT("sxjdfreight", "顺心捷达"),
    KUAIJIESUDI("kuaijiesudi", "快捷速递"),
    YUANTONGGUOJI("yuantongguoji", "圆通国际"),
    GSLHKD("gslhkd", "联合快递"),
    DISIFANG("disifang", "递四方"),
    RUNHENGFENG("runhengfeng", "全时速运"),
    MEIQUICK("meiquick", "美快国际物流"),
    YUXINWULIU("yuxinwuliu", "宇鑫物流"),
    TNT("tnt", "TNT"),
    ZHIMAKAIMEN("zhimakaimen", "芝麻开门"),
    UBONEX("ubonex", "优邦速运"),
    CHINAICIP("chinaicip", "卓志速运"),
    JAPANPOSTEN("japanposten", "日本（Japan Post）"),
    LONGBANWULIU("longbanwuliu", "龙邦速递"),
    YUNTRACK("yuntrack", "YUN TRACK"),
    FUJISUYUN("fujisuyun", "富吉速运"),
    FLYWAY("flyway", "程光快递"),
    AUSPOST("auspost", "澳大利亚(Australia Post)"),
    SUNJEX("sunjex", "新杰物流"),
    GUOTONGKUAIDI("guotongkuaidi", "国通快递"),
    DSUKUAIDI("dsukuaidi", "D速快递"),
    ANXL("anxl", "安迅物流"),
    HKEMS("hkems", "云邮跨境快递"),
    SANHUWULIU("sanhuwuliu", "叁虎物流"),
    SUTENG("suteng", "广东速腾物流"),
    ARKEXPRESS("arkexpress", "方舟速递"),
    WEITEPAI("weitepai", "微特派"),
    TIANDIHUAYU("tiandihuayu", "天地华宇"),
    RLGAUS("rlgaus", "澳洲飞跃物流"),
    LBEX("lbex", "龙邦物流"),
    TRANSRUSH("transrush", "TransRush"),
    HUISENKY("huisenky", "汇森速运"),
    ZHONGHUAN("zhonghuan", "中环快递"),
    PINGANDATENGFEI("pingandatengfei", "平安达腾飞"),
    SDTO("sdto", "速达通"),
    SAVOR("savor", "海信物流"),
    SUPERB("superb", "Superb Grace"),
    UNITEDEX("unitedex", "联合速运"),
    XLOBO("xlobo", "Xlobo贝海国际"),
    BANMA("banma", "斑马物流"),
    POLAREXPRESS("polarexpress", "极地快递"),
    BFLG("bflg", "上海缤纷物流"),
    CRAZYEXPRESS("crazyexpress", "疯狂快递"),
    SFWL("sfwl", "盛丰物流"),
    ANE66("ane66", "安能快递"),
    FTD("ftd", "富腾达国际货运"),
    AUOD("auod", "澳德物流"),
    ZHONGTIEWULIU("zhongtiewuliu", "中铁物流"),
    TNTEN("tnten", "TNT-全球件"),
    YUNTONG("yuntong", "运通速运"),
    HUANGMAJIA("huangmajia", "黄马甲"),
    JIAYUNMEIWULIU("jiayunmeiwuliu", "加运美"),
    LIANBANGKUAIDIEN("lianbangkuaidien", "联邦快递-英文"),
    HKPOST("hkpost", "中国香港(HongKong Post)"),
    WANJIAWULIU("wanjiawuliu", "万家物流"),
    VALUEWAY("valueway", "美通"),
    SHENGHUIWULIU("shenghuiwuliu", "盛辉物流"),
    ZHONGTONGPHONE("zhongtongphone", "中通（带电话）"),
    BPOST("bpost", "比利时（Bpost）"),
    LIJISONG("lijisong", "成都立即送"),
    WONDERSYD("wondersyd", "中邮速递"),
    WANXIANGWULIU("wanxiangwuliu", "万象物流"),
    ADAPOST("adapost", "安达速递"),
    RUFENGDA("rufengda", "如风达"),
    JINGSHUN("jingshun", "景顺物流"),
    UCS("ucs", "合众速递(UCS）"),
    POSTNLCN("postnlcn", "荷兰邮政-中文(PostNL international registered mail)"),
    TIANMA("tianma", "天马迅达"),
    SUT56("sut56", "速通物流"),
    GUANGDONGYOUZHENGWULIU("guangdongyouzhengwuliu", "广东邮政"),
    QEXPRESS("qexpress", "易达通快递"),
    STOEXPRESS("stoexpress", "美国申通"),
    DATIANWULIU("datianwuliu", "大田物流"),
    OCS("ocs", "OCS"),
    AAE("aae", "AAE-中国件"),
    AUSTA("austa", "Austa国际速递"),
    ZHONGSUKUAIDI("zhongsukuaidi", "中速快递"),
    UEQ("ueq", "UEQ快递"),
    FASTGOEXPRESS("fastgoexpress", "速派快递"),
    DPD("dpd", "DPD"),
    ZHENGYIKUAIDI("zhengyikuaidi", "鑫正一快递"),
    HAIDAIBAO("haidaibao", "海带宝"),
    HENGLUWULIU("hengluwuliu", "恒路物流"),
    SINGPOST("singpost", "新加坡小包(Singapore Post)"),
    UBUY("ubuy", "德国优拜物流"),
    BAIFUDONGFANG("baifudongfang", "百福东方"),
    CHNEXP("chnexp", "中翼国际物流"),
    EST365("est365", "东方汇"),
    ZJSTKY("zjstky", "苏通快运"),
    PJBEST("pjbest", "品骏快递"),
    ARAMEX("aramex", "Aramex"),
    YCGKY("ycgky", "远成快运"),
    CHANGJIANG("changjiang", "长江国际速递"),
    CHUKOU1("chukou1", "出口易"),
    HD("hd", "宏递快运"),
    DOORTODOOR("doortodoor", "CJ物流"),
    BSHT("bsht", "百事亨通"),
    BAZIRIM("bazirim", "皮牙子快递"),
    DEKUNCN("dekuncn", "德坤物流"),
    YUANANDA("yuananda", "源安达"),
    EMSINTEN("emsinten", "EMS-国际件-英文"),
    XUNSUEXPRESS("xunsuexpress", "迅速快递"),
    TNTAU("tntau", "TNT Australia"),
    XDEXPRESS("xdexpress", "迅达速递"),
    YANGBAOGUO("yangbaoguo", "洋包裹"),
    JINAN("jinan", "金岸物流"),
    MEIXI("meixi", "美西快递"),
    SHANGQIAO56("shangqiao56", "商桥物流"),
    FASTGO("fastgo", "速派快递(FastGo)"),
    FEDEXCN("fedexcn", "Fedex-国际件-中文"),
    SUJIEVIP("sujievip", "郑州速捷"),
    GUEXP("guexp", "全联速运"),
    ONEEXPRESS("oneexpress", "一速递"),
    TSTEXP("tstexp", "TST速运通"),
    EMSEN("emsen", "EMS-英文"),
    COE("coe", "COE"),
    JUMSTC("jumstc", "聚盟共建"),
    SENDTOCHINA("sendtochina", "速递中国"),
    NEWZEALAND("newzealand", "新西兰（New Zealand Post）"),
    ZHAIJIBIAN("zhaijibian", "宅急便"),
    USZCN("uszcn", "转运中国"),
    ZENGYISUDI("zengyisudi", "增益速递"),
    HUANQIU("huanqiu", "环球速运"),
    YTKD("ytkd", "运通中港快递"),
    YAFENGSUDI("yafengsudi", "亚风速递"),
    LA911("la911", "鼎润物流"),
    CNPEX("cnpex", "CNPEX中邮快递"),
    EUASIA("euasia", "欧亚专线"),
    EXFRESH("exfresh", "安鲜达"),
    QUANFENGKUAIDI("quanfengkuaidi", "全峰快递"),
    ZLXDJWL("zlxdjwl", "中粮鲜到家物流"),
    DFKUAIDI("dfkuaidi", "东风快递"),
    YOUYOU("youyou", "优优速递"),
    ANXINDAKUAIXI("anxindakuaixi", "安信达"),
    CANPOST("canpost", "加拿大(Canada Post)"),
    HNHT56("hnht56", "鸿泰物流"),
    JIALIDATONG("jialidatong", "嘉里大通"),
    EPANEX("epanex", "泛捷国际速递"),
    YZSWULIU("yzswuliu", "亚洲顺物流"),
    DPEX("dpex", "DPEX"),
    HAIZHONGZHUANYUN("haizhongzhuanyun", "海中转运"),
    JGWL("jgwl", "景光物流"),
    JIAYIWULIU("jiayiwuliu", "佳怡物流"),
    DEUTSCHEPOST("deutschepost", "德国(Deutsche Post)"),
    FEDEXUS("fedexus", "FedEx-美国件"),
    WESTWING("westwing", "西翼物流"),
    AOTSD("aotsd", "澳天速运"),
    HAC56("hac56", "瀚朝物流"),
    BECKYGO("beckygo", "佰麒快递"),
    JXFEX("jxfex", "集先锋快递"),
    YUNFENG56("yunfeng56", "韵丰物流"),
    HEXINEXPRESS("hexinexpress", "合心速递"),
    CORREOSDEES("correosdees", "西班牙(Correos de Espa?a)"),
    COLISSIMO("colissimo", "法国小包（colissimo）"),
    YAOFEIKUAIDI("yaofeikuaidi", "耀飞同城快递"),
    ZLINK("zlink", "三真驿道"),
    KOALAEXP("koalaexp", "考拉速递"),
    JIAJIWULIU("jiajiwuliu", "佳吉快运"),
    STOSOLUTION("stosolution", "申通国际"),
    KOREAPOST("koreapost", "韩国（Korea Post）"),
    HREX("hrex", "锦程快递"),
    JIGUANG("jiguang", "极光转运"),
    ONTRAC("ontrac", "OnTrac"),
    NZZTO("nzzto", "新西兰中通"),
    LASERSHIP("lasership", "LaserShip"),
    SD138("sd138", "泰国138国际物流"),
    MOSUDA("mosuda", "魔速达"),
    TCXBTHAI("tcxbthai", "TCXB国际物流"),
    SHUNFENGKUAIYUN("shunfengkuaiyun", "顺丰快运"),
    YOUSUTONGDA("yousutongda", "优速通达"),
    AMAZONCNORDER("amazoncnorder", "亚马逊中国订单"),
    SHIPGCE("shipgce", "飞洋快递"),
    PARCELFORCE("parcelforce", "英国大包、EMS（Parcel Force）"),
    LFEXPRESS("lfexpress", "龙枫国际快递"),
    LONGFX("longfx", "LUCFLOW EXPRESS"),
    XYNYC("xynyc", "新元国际"),
    EFS("efs", "EFS Post（平安快递）"),
    DPEXEN("dpexen", "Toll"),
    FEIYUANVIPSHOP("feiyuanvipshop", "飞远配送"),
    CNEXPS("cnexps", "CNE"),
    YTCHENGNUODA("ytchengnuoda", "承诺达"),
    FTKY365("ftky365", "丰通快运"),
    TCAT("tcat", "黑猫宅急便"),
    SHUNFENGHK("shunfenghk", "顺丰-繁体"),
    CHSZHONGHUANGUOJI("chszhonghuanguoji", "CHS中环国际快递"),
    ECMSCN("ecmscn", "易客满"),
    SYNSHIP("synship", "SYNSHIP快递"),
    DHLBENELUX("dhlbenelux", "DHL Benelux"),
    CSUIVI("csuivi", "法国(La Poste)"),
    TZKY("tzky", "铁中快运"),
    ZHONGCHUAN("zhongchuan", "众川国际"),
    SAGAWA("sagawa", "佐川急便"),
    YIZHENGDASUYUN("yizhengdasuyun", "一正达速运"),
    GOTOUBI("gotoubi", "UBI Australia"),
    YUANCHENGWULIU("yuanchengwuliu", "远成物流"),
    ITALIANE("italiane", "意大利(Poste Italiane)"),
    QUANYIKUAIDI("quanyikuaidi", "全一快递"),
    SHANGDA("shangda", "上大物流"),
    TOPSPEEDEX("topspeedex", "中运全速"),
    GANZHONGNENGDA("ganzhongnengda", "能达速递"),
    COM1EXPRESS("com1express", "商壹国际物流"),
    LINEONE("lineone", "一号线"),
    TNJEX("tnjex", "明通国际快递"),
    ZTEEXPRESS("zteexpress", "ZTE中兴物流"),
    CNAUSU("cnausu", "中澳速递"),
    DAYANGWULIU("dayangwuliu", "大洋物流"),
    NDWL("ndwl", "南方传媒物流"),
    MINGHANGKUAIDI("minghangkuaidi", "民航快递"),
    WHEREXPESS("wherexpess", "威盛快递"),
    HTTX56("httx56", "汇通天下物流"),
    JAPANPOST("japanpost", "日本郵便"),
    SUNDAREXPRESS("sundarexpress", "顺达快递"),
    SPEEDPOST("speedpost", "新加坡EMS、大包(Singapore Speedpost)"),
    ANJIE88("anjie88", "安捷物流"),
    TYWL99("tywl99", "天翼物流"),
    JIACHENG("jiacheng", "佳成快递"),
    JIAJIKUAIDI("jiajikuaidi", "佳吉快递"),
    BEEBIRD("beebird", "锋鸟物流"),
    SXEXPRESS("sxexpress", "三象速递"),
    PEISIHUOYUNKUAIDI("peisihuoyunkuaidi", "配思货运"),
    POSTNL("postnl", "荷兰邮政(PostNL international registered mail)"),
    WLWEX("wlwex", "星空国际"),
    CHENGPEI("chengpei", "河北橙配"),
    NANJINGSHENGBANG("nanjingshengbang", "晟邦物流"),
    BAITENGWULIU("baitengwuliu", "百腾物流"),
    AIRPAK("airpak", "airpak expresss"),
    QUANSUTONG("quansutong", "全速通"),
    THAILAND("thailand", "泰国（Thailand Thai Post）"),
    JIAJIAWL("jiajiawl", "加佳物流"),
    TRAKPAK("trakpak", "TRAKPAK"),
    KINGFREIGHT("kingfreight", "货运皇"),
    CAMEROON("cameroon", "喀麦隆(CAMPOST)"),
    RUIDIANYOUZHENG("ruidianyouzheng", "瑞典（Sweden Post）"),
    SPRING56("spring56", "春风物流"),
    USCBEXPRESS("uscbexpress", "易境达国际物流"),
    MALAYSIAPOST("malaysiapost", "马来西亚小包（Malaysia Post(Registered)）"),
    SHLINDAO("shlindao", "林道国际快递"),
    COSCO("cosco", "中远e环球"),
    JIUJIUWL("jiujiuwl", "久久物流"),
    EMSWULIU("emswuliu", "EMS物流"),
    SHANGCHENG("shangcheng", "尚橙物流"),
    WULIUKY("wuliuky", "五六快运"),
    DECHUANGWULIU("dechuangwuliu", "深圳德创物流"),
    GXWL("gxwl", "光线速递"),
    HERMES("hermes", "Hermes"),
    NEBUEX("nebuex", "星云速递"),
    ASENDIAUSA("asendiausa", "Asendia USA"),
    JIEANDA("jieanda", "捷安达"),
    QINYUAN("qinyuan", "秦远物流"),
    QPOST("qpost", "卡塔尔（Qatar Post）"),
    CLLEXPRESS("cllexpress", "澳通华人物流"),
    GLOBALTRACKTRACE("globaltracktrace", "globaltracktrace"),
    GTS("gts", "GTS快递"),
    HRE("hre", "高铁速递"),
    TYKD("tykd", "天翼快递"),
    POSTSERV("postserv", "台湾（中华邮政）"),
    SHPOSTWISH("shpostwish", "wish邮"),
    YUFENG("yufeng", "御风速运"),
    WJKWL("wjkwl", "万家康物流"),
    XIYOUG("xiyoug", "西游寄"),
    A2U("a2u", "A2U速递"),
    ONEHCANG("onehcang", "一号仓"),
    ANPOSTEN("anposten", "爱尔兰(An Post)"),
    JIAZHOUMAO("jiazhoumao", "加州猫速递"),
    HLYEX("hlyex", "好来运"),
    WYKJT("wykjt", "51跨境通"),
    YOUBAN("youban", "邮邦国际"),
    CHENGTONG("chengtong", "城通物流"),
    DHLDE("dhlde", "DHL-德国件（DHL Deutschland）"),
    FLYSMAN("flysman", "飞力士物流"),
    SLOVENIA("slovenia", "斯洛文尼亚(Slovenia Post)"),
    ZF365("zf365", "珠峰速运"),
    EXSUDA("exsuda", "E速达"),
    WTDCHINA("wtdchina", "威时沛运货运"),
    CHUANGYI("chuangyi", "创一快递"),
    DFWL("dfwl", "达发物流"),
    HEIMAO56("heimao56", "黑猫速运"),
    UKRPOSTCN("ukrpostcn", "乌克兰邮政包裹"),
    ZHONGJIWULIU("zhongjiwuliu", "中技物流"),
    BHT("bht", "BHT"),
    BULGARIAN("bulgarian", "保加利亚（Bulgarian Posts）"),
    MORELINK56("morelink56", "MoreLink"),
    QUANJITONG("quanjitong", "全际通"),
    CHT361("cht361", "诚和通"),
    FEIKANGDA("feikangda", "飞康达"),
    GSM("gsm", "GSM"),
    BOYOL("boyol", "贝业物流"),
    HLTOP("hltop", "海联快递"),
    ESHUNDA("eshunda", "俄顺达"),
    GUOERYUE("guoeryue", "天天快物流"),
    MEIGUOKUAIDI("meiguokuaidi", "美国快递"),
    SZYOUZHENG("szyouzheng", "深圳邮政"),
    USPSCN("uspscn", "USPSCN"),
    YIDATONG("yidatong", "易达通"),
    ZHONGHUANUS("zhonghuanus", "中环转运"),
    DINGDONG("dingdong", "叮咚快递"),
    EASYEXPRESS("easyexpress", "EASY EXPRESS"),
    SHENGANWULIU("shenganwuliu", "圣安物流"),
    VPS("vps", "维普恩物流"),
    SWISSPOST("swisspost", "瑞士(Swiss Post)"),
    AOLAU("aolau", "AOL澳通速递"),
    POCHTA("pochta", "俄罗斯邮政(Russian Post)"),
    TAOPLUS("taoplus", "淘布斯国际物流"),
    ZHONGTIANWANYUN("zhongtianwanyun", "中天万运"),
    NEDERLANDPOST("nederlandpost", "荷兰速递(Nederland Post)"),
    ZSKY123("zsky123", "准实快运"),
    BANGSONGWULIU("bangsongwuliu", "邦送物流"),
    BENTENG("benteng", "奔腾物流"),
    BYHT("byht", "展勤快递"),
    ETONG("etong", "E通速递"),
    KENYA("kenya", "肯尼亚(POSTA KENYA)"),
    PFCEXPRESS("pfcexpress", "皇家物流"),
    TRACKPARCEL("trackparcel", "track-parcel"),
    UHI("uhi", "优海国际速递"),
    HONGYWL("hongywl", "红远物流"),
    IDAMALU("idamalu", "大马鹿"),
    POSTNLCHINA("postnlchina", "荷兰邮政-中国件"),
    ZDEPOST("zdepost", "直德邮"),
    EMMS("emms", "澳州顺风快递"),
    JCSUDA("jcsuda", "嘉诚速达"),
    MINGLIANGWULIU("mingliangwuliu", "明亮物流"),
    MMLOGI("mmlogi", "猛犸速递"),
    NEWSWAY("newsway", "家家通快递"),
    ABF("abf", "ABF"),
    ASTEXPRESS("astexpress", "安世通快递"),
    CHUANXIWULIU("chuanxiwuliu", "传喜物流"),
    CHUNGHWA56("chunghwa56", "中骅物流"),
    FARLOGISTIS("farlogistis", "泛远国际物流"),
    HKPOSTEN("hkposten", "中国香港(HongKong Post)英文"),
    HNFY("hnfy", "飞鹰物流"),
    HT22("ht22", "海淘物流"),
    QBEXPRESS("qbexpress", "秦邦快运"),
    WTO56KJ("wto56kj", "臣邦同城"),
    YINGCHAO("yingchao", "英超物流"),
    YONGCHANGWULIU("yongchangwuliu", "永昌物流"),
    SANTAISUDI("santaisudi", "三态速递"),
    SHUNJIEDA("shunjieda", "顺捷达"),
    TMWEXPRESS("tmwexpress", "明达国际速递"),
    BLUESKYEXPRESS("blueskyexpress", "蓝天快递"),
    CITYLINK("citylink", "City-Link"),
    HOMECOURIER("homecourier", "如家国际快递"),
    JIEBORNE("jieborne", "捷邦物流"),
    LUBEN("luben", "陆本速递 LUBEN EXPRESS"),
    NELL("nell", "尼尔快递"),
    PCAEXPRESS("pcaexpress", "PCA Express"),
    SUNSPEEDY("sunspeedy", "新速航"),
    SZUEM("szuem", "联运通物流"),
    VNPOST("vnpost", "越南EMS(VNPost Express)"),
    ZTONG("ztong", "智通物流"),
    ADP("adp", "ADP国际快递"),
    BJEMSTCKJ("bjemstckj", "北京EMS"),
    LTX("ltx", "蓝天国际快递"),
    SCCOD("sccod", "丰程物流"),
    YUEFENGWULIU("yuefengwuliu", "越丰物流"),
    CTOEXP("ctoexp", "泰国中通CTO"),
    HANGRUI("hangrui", "上海航瑞货运"),
    HHAIR56("hhair56", "华瀚快递"),
    JIXIANDA("jixianda", "急先达"),
    KERRYTJ("kerrytj", "嘉里大荣物流"),
    YDGLOBE("ydglobe", "云达通"),
    YDHEX("ydhex", "YDH"),
    ANJIEKUAIDI("anjiekuaidi", "青岛安捷快递"),
    CHINAPOSTCB("chinapostcb", "中邮电商"),
    EUPACKAGE("eupackage", "易优包裹"),
    FEIBAOKUAIDI("feibaokuaidi", "飞豹快递"),
    GSLEXPRESS("gslexpress", "德尚国际速递"),
    JAMAICAPOST("jamaicapost", "牙买加（Jamaica Post）"),
    MYHERMES("myhermes", "MyHermes"),
    SIGNEDEXPRESS("signedexpress", "签收快递"),
    YUE777("yue777", "玥玛速运"),
    ZSMHWL("zsmhwl", "明辉物流"),
    ADVANCING("advancing", "安达信"),
    BIAOJIKUAIDI("biaojikuaidi", "彪记快递"),
    GONGSUDA("gongsuda", "共速达"),
    KEJIE("kejie", "科捷物流"),
    MACAO("macao", "中国澳门(Macau Post)"),
    SHUNJIEFENGDA("shunjiefengda", "顺捷丰达"),
    YNZTSY("ynztsy", "纵通速运"),
    YUJIAWL("yujiawl", "宇佳物流"),
    YUNTONGKUAIDI("yuntongkuaidi", "运通中港"),
    ZITON("1ziton", "一智通"),
    BDATONG("bdatong", "八达通"),
    BUYTONG("buytong", "百通物流"),
    CHANGYUWULIU("changyuwuliu", "长宇物流"),
    FBKD("fbkd", "飞邦快递"),
    FOX("fox", "FOX国际快递"),
    GHTEXPRESS("ghtexpress", "GHT物流"),
    GOODAY365("gooday365", "日日顺智慧物联"),
    ADAEXPRESS("adaexpress", "明大快递"),
    AIRGTC("airgtc", "航空快递"),
    CANHOLD("canhold", "能装能送"),
    CNSPEEDSTER("cnspeedster", "速舟物流"),
    EFSPOST("efspost", "EFSPOST"),
    FANYUKUAIDI("fanyukuaidi", "凡宇快递"),
    FASTONTIME("fastontime", "加拿大联通快运"),
    HUMPLINE("humpline", "驼峰国际"),
    JCEX("jcex", "jcex"),
    PAKISTAN("pakistan", "巴基斯坦(Pakistan Post)"),
    POSTNLPACLE("postnlpacle", "荷兰包裹(PostNL International Parcels)"),
    QICHEN("qichen", "启辰国际速递"),
    QUANSU("quansu", "全速物流"),
    RIYUWULIU("riyuwuliu", "日昱物流"),
    TNTUK("tntuk", "TNT UK"),
    YIQISONG("yiqisong", "一起送"),
    ABCGLOBAL("abcglobal", "全球快运"),
    AHDF("ahdf", "德方物流"),
    CHENGDA("chengda", "成达国际速递"),
    COMEXPRESS("comexpress", "邦通国际"),
    DHLHK("dhlhk", "DHL HK"),
    DIANTONGKUAIDI("diantongkuaidi", "店通快递"),
    DISIFANGAU("disifangau", "递四方澳洲"),
    HAIHONGWANGSONG("haihongwangsong", "海红网送"),
    HOTWMS("hotwms", "皇家云仓"),
    JINDAWULIU("jindawuliu", "金大物流"),
    MALAYSIAEMS("malaysiaems", "马来西亚大包、EMS（Malaysia Post(parcel,EMS)）"),
    QUANCHUAN56("quanchuan56", "全川物流"),
    QUANRITONGKUAIDI("quanritongkuaidi", "全日通"),
    SFIFT("sfift", "十方通物流"),
    SXHONGMAJIA("sxhongmajia", "红马甲物流"),
    XIANGLONGYUNTONG("xianglongyuntong", "祥龙运通物流"),
    XSRD("xsrd", "鑫世锐达"),
    YUANZHIJIECHENG("yuanzhijiecheng", "元智捷诚"),
    ZSDA56("zsda56", "转瞬达集运"),
    ADLERLOGI("adlerlogi", "德国雄鹰速递"),
    ALBANIA("albania", "阿尔巴尼亚(Posta shqipatre)"),
    APLUSEX("aplusex", "Aplus物流"),
    AUEX("auex", "澳货通"),
    AUSBONDEXPRESS("ausbondexpress", "澳邦国际物流"),
    AUSEXPRESS("ausexpress", "澳世速递"),
    BEE001("bee001", "蜜蜂速递"),
    BPOSTINTER("bpostinter", "比利时国际(Bpost international)"),
    CCES("cces", "CCES/国通快递"),
    CKEEX("ckeex", "城晓国际快递"),
    CNAIR("cnair", "CNAIR"),
    DONGJUN("dongjun", "成都东骏物流"),
    FENGHUANGKUAIDI("fenghuangkuaidi", "凤凰快递"),
    FREAKYQUICK("freakyquick", "FQ狂派速递"),
    GDKJK56("gdkjk56", "快捷快物流"),
    GOLDJET("goldjet", "高捷快运"),
    HONGBEIXIN("hongbeixin", "红背心"),
    HUAQIKUAIYUN("huaqikuaiyun", "华企快运"),
    HUNGARY("hungary", "匈牙利（Magyar Posta）"),
    IDADA("idada", "大达物流"),
    IYOUNGSPEED("iyoungspeed", "驿扬国际速运"),
    KAOLAEXPRESS("kaolaexpress", "考拉国际速递"),
    MCHY("mchy", "木春货运"),
    MINBANGSUDI("minbangsudi", "民邦速递"),
    PARCELCHINA("parcelchina", "诚一物流"),
    RPX("rpx", "rpx"),
    RRSKX("rrskx", "日日顺快线"),
    SAIAODIMMB("saiaodimmb", "赛澳递for买卖宝"),
    SDSY888("sdsy888", "首达速运"),
    SOUTHAFRICAN("southafrican", "南非（South African Post Office）"),
    TONGHETIANXIA("tonghetianxia", "通和天下"),
    YUNDAEXUS("yundaexus", "美国云达"),
    YYQC56("yyqc56", "一运全成物流"),
    ZTJIEDA("ztjieda", "泰捷达国际物流"),
    AHKBPS("ahkbps", "卡邦配送"),
    AJEXPRESS("ajexpress", "捷记方舟"),
    BAISHIYP("baishiyp", "百世云配"),
    BARBADOS("barbados", "巴巴多斯(Barbados Post)"),
    BELGIUMPOST("belgiumpost", "比利时(Belgium Post)"),
    BELIZE("belize", "伯利兹(Belize Postal)"),
    BJXSRD("bjxsrd", "鑫锐达"),
    BLUEDART("bluedart", "BlueDart"),
    CHINATZX("chinatzx", "同舟行物流"),
    CNCEXP("cncexp", "C&C国际速递"),
    DADAOEX("dadaoex", "大道物流"),
    DHLECOMMERCE("dhlecommerce", "dhl小包"),
    DPDGERMANY("dpdgermany", "DPD Germany"),
    EDTEXPRESS("edtexpress", "e直运"),
    EUEXPRESS("euexpress", "EU-EXPRESS"),
    EUGUOJI("euguoji", "易邮国际"),
    EXPRESS7TH("express7th", "7号速递"),
    FEIHUKUAIDI("feihukuaidi", "飞狐快递"),
    HYYTES("hyytes", "恒宇运通"),
    IPARCEL("iparcel", "UPS i-parcel"),
    KAZPOST("kazpost", "哈萨克斯坦(Kazpost)"),
    NAMIBIA("namibia", "纳米比亚(NamPost)"),
    PENGCHENG("pengcheng", "鹏程快递"),
    POSTPNG("postpng", "巴布亚新几内亚(PNG Post)"),
    PUROLATOR("purolator", "Purolator"),
    QIANLI("qianli", "千里速递"),
    SAIAODI("saiaodi", "赛澳递"),
    SINOAIRINEX("sinoairinex", "中外运空运"),
    STKD("stkd", "顺通快递"),
    TAIJIN("taijin", "泰进物流"),
    TONGDAXING("tongdaxing", "通达兴物流"),
    WANDOUGONGZHU("wandougongzhu", "豌豆物流"),
    XIANGDAWULIU("xiangdawuliu", "湘达物流"),
    XIAOCEX("xiaocex", "小C海淘"),
    YIEX("yiex", "宜送物流"),
    YINJIESUDI("yinjiesudi", "银捷速递"),
    YIOUZHOU("yiouzhou", "易欧洲国际物流"),
    YODEL("yodel", "YODEL"),
    YTKY168("ytky168", "运通快运"),
    YUEZHONGSH("yuezhongsh", "粤中国际货运代理（上海）有限公司"),
    ZHDWL("zhdwl", "众辉达物流"),
    ZHONGXINDA("zhongxinda", "忠信达"),
    ALOG("alog", "心怡物流"),
    AMUSORDER("amusorder", "amazon-国际订单"),
    AOSU("aosu", "澳速物流"),
    AUVANDA("auvanda", "中联速递"),
    BANGLADESH("bangladesh", "孟加拉国(EMS)"),
    BELPOST("belpost", "白俄罗斯(Belpochta)"),
    BENNIAO("benniao", "笨鸟国际"),
    BQCWL("bqcwl", "百千诚物流"),
    CAMBODIA("cambodia", "柬埔寨(Cambodia Post)"),
    CANPOSTFR("canpostfr", "加拿大邮政"),
    CESKAPOSTA("ceskaposta", "捷克（?eská po?ta）"),
    CEVALOGISTICS("cevalogistics", "CEVA Logistic"),
    CFSS("cfss", "银雁专送"),
    CHANGWOOAIR("changwooair", "昌宇国际"),
    CHINASQK("chinasqk", "SQK国际速递"),
    CHRONOPOSTFRA("chronopostfra", "法国大包、EMS-法文（Chronopost France）"),
    CORREOS("correos", "哥斯达黎加(Correos de Costa Rica)"),
    CZWLYN("czwlyn", "云南诚中物流"),
    DFPOST("dfpost", "达方物流"),
    DHLNETHERLANDS("dhlnetherlands", "DHL-荷兰（DHL Netherlands）"),
    DIDASUYUN("didasuyun", "递达速运"),
    DPDPOLAND("dpdpoland", "DPD Poland"),
    EL56("el56", "易联通达"),
    ESINOTRANS("esinotrans", "中外运"),
    EUCPOST("eucpost", "德国 EUC POST"),
    EUSACN("eusacn", "优莎速运"),
    EXCOCOTREE("excocotree", "可可树美中速运"),
    FYEX("fyex", "飞云快递系统"),
    HAIMENGSUDI("haimengsudi", "海盟速递"),
    HANGYU("hangyu", "航宇快递"),
    HAOYOUKUAI("haoyoukuai", "好又快物流"),
    HAPPYLINK("happylink", "开心快递"),
    HUADA("huada", "华达快运"),
    HUANQIUABC("huanqiuabc", "中国香港环球快运"),
    HUAXIAHUOYUN("huaxiahuoyun", "华夏货运"),
    HUOBAN("huoban", "兰州伙伴物流"),
    JUDING("juding", "聚鼎物流"),
    JUNFENGGUOJI("junfengguoji", "骏丰国际速递"),
    KCS("kcs", "KCS"),
    KJDE("kjde", "跨境直邮通"),
    KOREAPOSTCN("koreapostcn", "韩国邮政"),
    KUAI8("kuai8", "快8速运"),
    LESOTHO("lesotho", "莱索托(Lesotho Post)"),
    LITHUANIA("lithuania", "立陶宛（Lietuvos pa?tas）"),
    LITTLEBEARBEAR("littlebearbear", "小熊物流"),
    LONGLANGKUAIDI("longlangkuaidi", "隆浪快递"),
    LONGVAST("longvast", "长风物流"),
    LSEXPRESS("lsexpress", "6LS EXPRESS"),
    LUCKYFASTEX("luckyfastex", "吉捷国际速递"),
    MAXEEDEXPRESS("maxeedexpress", "澳洲迈速快递"),
    MOLDOVA("moldova", "摩尔多瓦(Posta Moldovei)"),
    MONTENEGRO("montenegro", "黑山(Posta Crne Gore)"),
    NLEBV("nlebv", "亚欧专线"),
    OCAARGEN("ocaargen", "OCA Argentina"),
    PARCELFORCECN("parcelforcecn", "英国邮政大包EMS"),
    POSTA("posta", "坦桑尼亚（Tanzania Posts Corporation）"),
    SANSHENGCO("sanshengco", "三盛快递"),
    SCIC("scic", "中加国际快递"),
    SCZPDS("sczpds", "速呈"),
    SFJHD("sfjhd", "圣飞捷快递"),
    SHUNBANG("shunbang", "顺邦国际物流"),
    SHUNSHID("shunshid", "顺士达速运"),
    SKYNETMALAYSIA("skynetmalaysia", "SkyNet Malaysia"),
    SUCMJ("sucmj", "特急便物流"),
    THAIZTO("thaizto", "泰国中通ZTO"),
    TIANZONG("tianzong", "天纵物流"),
    TURTLE("turtle", "海龟国际快递"),
    UEXIEX("uexiex", "欧洲UEX"),
    ULUCKEX("uluckex", "优联吉运"),
    UPSFREIGHT("upsfreight", "UPS Freight"),
    UZBEKISTAN("uzbekistan", "乌兹别克斯坦(Post of Uzbekistan)"),
    VANGENEXPRESS("vangenexpress", "万庚国际速递"),
    VCTRANS("vctrans", "越中国际物流"),
    WENJIESUDI("wenjiesudi", "文捷航空"),
    WLFAST("wlfast", "凡仕特物流"),
    YEMEN("yemen", "也门(Yemen Post)"),
    YHTLOGISTICS("yhtlogistics", "宇航通物流"),
    YIFANKD("yifankd", "艺凡快递"),
    YOULAI("youlai", "邮来速递"),
    YPSD("ypsd", "壹品速递"),
    YUANHHK("yuanhhk", "远航国际快运"),
    YUNEXPRESS("yunexpress", "德国云快递"),
    YW56("yw56", "燕文物流"),
    YYEXP("yyexp", "西安运逸快递"),
    ZHONGWAIYUN("zhongwaiyun", "中外运速递"),
    ZHPEX("zhpex", "众派速递"),
    ZJGJ56("zjgj56", "振捷国际货运"),
    ADIEXPRESS("adiexpress", "安达易国际速递"),
    AFGHAN("afghan", "阿富汗(Afghan Post)"),
    AFL("afl", "AFL"),
    AGOPOST("agopost", "全程快递"),
    ALIEXPRESS("aliexpress", "无忧物流"),
    AMCNORDER("amcnorder", "amazon-国内订单"),
    ANJIATONGCHENG("anjiatongcheng", "安家同城快运"),
    ANLEXPRESS("anlexpress", "新干线快递"),
    APGECOMMERCE("apgecommerce", "apgecommerce"),
    APLUS100("aplus100", "美国汉邦快递"),
    ARIESFAR("ariesfar", "艾瑞斯远"),
    ARUBA("aruba", "阿鲁巴[荷兰]（Post Aruba）"),
    AUSTRIA("austria", "奥地利(Austrian Post)"),
    AUVEXPRESS("auvexpress", "AUV国际快递"),
    AXEXPRESS("axexpress", "澳新物流"),
    AZERBAIJAN("azerbaijan", "阿塞拜疆EMS(EMS AzerExpressPost)"),
    BAHRAIN("bahrain", "巴林(Bahrain Post)"),
    BANGBANGPOST("bangbangpost", "帮帮发"),
    BAOTONGKD("baotongkd", "宝通快递"),
    BAOXIANDA("baoxianda", "报通快递"),
    BCWELT("bcwelt", "BCWELT"),
    BESTER("bester", "飛斯特"),
    BJQYWL("bjqywl", "青云物流"),
    BMLCHINA("bmlchina", "标杆物流"),
    BOHEI("bohei", "波黑(JP BH Posta)"),
    BOLIVIA("bolivia", "玻利维亚"),
    BORDERGURU("borderguru", "BorderGuru"),
    BOSIND("bosind", "堡昕德速递"),
    BOTSPOST("botspost", "博茨瓦纳"),
    BPHCHINA("bphchina", "速方(Sufast)"),
    BRAZILPOSTEN("brazilposten", "巴西(Brazil Post/Correios)"),
    BRUNEI("brunei", "文莱(Brunei Postal)"),
    CALEDONIA("caledonia", "新喀里多尼亚[法国](New Caledonia)"),
    CAMEKONG("camekong", "到了港"),
    CAMPBELLSEXPRESS("campbellsexpress", "Campbell’s Express"),
    CANPAR("canpar", "Canpar"),
    CARGOLUX("cargolux", "卢森堡航空"),
    CBO56("cbo56", "钏博物流"),
    CCCC58("cccc58", "中集冷云"),
    CCD("ccd", "河南次晨达"),
    CDEK("cdek", "CDEK"),
    CDXINCHEN56("cdxinchen56", "鑫宸物流"),
    CEX("cex", "城铁速递"),
    CHENGJI("chengji", "城际快递"),
    CHILE("chile", "智利(Correos Chile)"),
    CHINASTARLOGISTICS("chinastarlogistics", "华欣物流"),
    CHLLOG("chllog", "嘉荣物流"),
    CHRONOPOSTFREN("chronopostfren", "法国大包、EMS-英文(Chronopost France)"),
    CHRONOPOSTPORT("chronopostport", "Chronopost Portugal"),
    CHUNFAI("chunfai", "中国香港骏辉物流"),
    CITY56("city56", "城市映急"),
    CITYSPRINT("citysprint", "citysprint"),
    CJKOREAEXPRESS("cjkoreaexpress", "大韩通运"),
    CLOUDEXPRESS("cloudexpress", "CE易欧通国际速递"),
    CLSP("clsp", "CL日中速运"),
    CNEULOGISTICS("cneulogistics", "中欧物流"),
    CNUP("cnup", "CNUP 中联邮"),
    CNWS("cnws", "中国翼"),
    COLOMBIA("colombia", "哥伦比亚(4-72 La Red Postal de Colombia)"),
    CORREIOS("correios", "莫桑比克（Correios de Moçambique）"),
    CORREO("correo", "乌拉圭（Correo Uruguayo）"),
    CORREOARGENTINO("correoargentino", "阿根廷(Correo Argentina)"),
    CPSAIR("cpsair", "华中快递"),
    CQXINGCHENG("cqxingcheng", "重庆星程快递"),
    CROSSBOX("crossbox", "环旅快运"),
    CSXSS("csxss", "新时速物流"),
    CYPRUSPOST("cypruspost", "塞浦路斯(Cyprus Post)"),
    DANDE56("dande56", "丹递56"),
    DASU("dasu", "达速物流"),
    DCS("dcs", "DCS"),
    DECNLH("decnlh", "德中快递"),
    DELTEC("deltec", "Deltec Courier"),
    DESWORKS("desworks", "澳行快递"),
    DHLPOLAND("dhlpoland", "DHL-波兰（DHL Poland）"),
    DI5PLL("di5pll", "递五方云仓"),
    DIANYI("dianyi", "云南滇驿物流"),
    DINDON("dindon", "叮咚澳洲转运"),
    DIRECTLINK("directlink", "Direct Link"),
    DISIFANGUS("disifangus", "递四方美国"),
    DJY56("djy56", "天翔东捷运"),
    DONGHANWL("donghanwl", "东瀚物流"),
    DONGHONG("donghong", "东红物流"),
    DPDUK("dpduk", "DPD UK"),
    DTDCINDIA("dtdcindia", "DTDC India"),
    DUODAO56("duodao56", "duodao56"),
    EALCEAIR("ealceair", "东方航空物流"),
    ECALLTURN("ecallturn", "E跨通"),
    ECFIRSTCLASS("ecfirstclass", "EC-Firstclass"),
    ECMSGLOBAL("ecmsglobal", "ECMS Express"),
    ECOTRANSITE("ecotransite", "东西E全运"),
    ECUADOR("ecuador", "厄瓜多尔(Correos del Ecuador)"),
    EDAEUEXPRESS("edaeuexpress", "易达快运"),
    EDRAGON("edragon", "龙象国际物流"),
    EGYPT("egypt", "埃及（Egypt Post）"),
    EIFFEL("eiffel", "艾菲尔国际速递"),
    ELTA("elta", "希腊包裹（ELTA Hellenic Post）"),
    ELTAHELL("eltahell", "希腊EMS（ELTA Courier）"),
    EMIRATES("emirates", "阿联酋(Emirates Post)"),
    EMONITORING("emonitoring", "波兰小包(Poczta Polska)"),
    EMSSOUTHAFRICA("emssouthafrica", "南非EMS"),
    EMSUKRAINE("emsukraine", "乌克兰EMS(EMS Ukraine)"),
    EMSUKRAINECN("emsukrainecn", "乌克兰EMS-中文(EMS Ukraine)"),
    ENGLAND("england", "英国(大包,EMS)"),
    EPSPOST("epspost", "联众国际"),
    ESTAFETA("estafeta", "Estafeta"),
    ESTES("estes", "Estes"),
    ETA100("eta100", "易达国际速递"),
    ETHIOPIA("ethiopia", "埃塞俄比亚(Ethiopian postal)"),
    EUCNRAIL("eucnrail", "中欧国际物流"),
    EUROPE8("europe8", "败欧洲"),
    EUROPEANECOM("europeanecom", "europeanecom"),
    EXPRESSPLUS("expressplus", "澳洲新干线快递"),
    EZHUANYUAN("ezhuanyuan", "易转运"),
    FANDAGUOJI("fandaguoji", "颿达国际快递-英文"),
    FARDARWW("fardarww", "颿达国际快递"),
    FASTWAY("fastway", "Fastway Ireland"),
    FASTZT("fastzt", "正途供应链"),
    FEDEXUK("fedexuk", "FedEx-英国件（FedEx UK)"),
    FEDEXUKCN("fedexukcn", "FedEx-英国件"),
    FEDROAD("fedroad", "FedRoad 联邦转运"),
    FEIKUAIDA("feikuaida", "飞快达"),
    FENGYEE("fengyee", "丰羿"),
    FIJI("fiji", "斐济(Fiji Post)"),
    FINLAND("finland", "芬兰(Itella Posti Oy)"),
    FLOWERKD("flowerkd", "花瓣转运"),
    FSEXP("fsexp", "全速快递"),
    FTLEXPRESS("ftlexpress", "法翔速运"),
    GAOTIEEX("gaotieex", "高铁快运"),
    GATICN("gaticn", "Gati-中文"),
    GATIEN("gatien", "Gati-英文"),
    GATIKWE("gatikwe", "Gati-KWE"),
    GDA("gda", "安的快递"),
    GDCT56("gdct56", "广东诚通物流"),
    GDQWWL("gdqwwl", "全网物流"),
    GDRZ58("gdrz58", "容智快运"),
    GDXP("gdxp", "新鹏快递"),
    GE2D("ge2d", "GE2D跨境物流"),
    GEORGIANPOST("georgianpost", "格鲁吉亚(Georgian Pos）"),
    GHL("ghl", "环创物流"),
    GIBRALTAR("gibraltar", "直布罗陀[英国]( Royal Gibraltar Post)"),
    GJWL("gjwl", "冠捷物流"),
    GLS("gls", "GLS"),
    GML("gml", "英脉物流"),
    GREENLAND("greenland", "格陵兰[丹麦]（TELE Greenland A/S）"),
    GRIVERTEK("grivertek", "潍鸿"),
    GSCQ365("gscq365", "哥士传奇速递"),
    GSWTKD("gswtkd", "万通快递"),
    GTGOGO("gtgogo", "GT国际快运"),
    GTONGSUDI("gtongsudi", "广通速递"),
    GTTEXPRESS("gttexpress", "GTT EXPRESS快递"),
    GUANGDONGTONGLU("guangdongtonglu", "广东通路"),
    GUANTING("guanting", "冠庭国际物流"),
    GUOSONG("guosong", "国送快运"),
    GVPEXPRESS("gvpexpress", "宏观国际快递"),
    GZXINGCHENG("gzxingcheng", "贵州星程快递"),
    HAIHONGMMB("haihongmmb", "海红for买卖宝"),
    HAIWAIHUANQIU("haiwaihuanqiu", "海外环球"),
    HAIXINGQIAO("haixingqiao", "海星桥快递"),
    HANDBOY("handboy", "汉邦国际速递"),
    HANFENGJL("hanfengjl", "翰丰快递"),
    HAYPOST("haypost", "亚美尼亚(Haypost-Armenian Postal)"),
    HENGRUI56("hengrui56", "恒瑞物流"),
    HGY56("hgy56", "环国运物流"),
    HIGHSINCE("highsince", "Highsince"),
    HITAOE("hitaoe", "Hi淘易快递"),
    HJS("hjs", "猴急送"),
    HLKYTJ("hlkytj", "互联快运"),
    HLPGYL("hlpgyl", "共联配"),
    HMUS("hmus", "华美快递"),
    HNQST("hnqst", "河南全速通"),
    HNSSD56("hnssd56", "顺时达物流"),
    HNZQWL("hnzqwl", "中强物流"),
    HOMEXPRESS("homexpress", "居家通"),
    HONGJIE("hongjie", "宏捷国际物流"),
    HONGPINWULIU("hongpinwuliu", "宏品物流"),
    HQTD("hqtd", "环球通达"),
    HRBZYKD("hrbzykd", "卓烨快递"),
    HRVATSKA("hrvatska", "克罗地亚（Hrvatska Posta）"),
    HSGTSD("hsgtsd", "海硕高铁速递"),
    HTONGEXPRESS("htongexpress", "华通快运"),
    HTWD("htwd", "华通务达物流"),
    HUANDONGLG("huandonglg", "环东物流"),
    HUIQIANGKUAIDI("huiqiangkuaidi", "汇强快递"),
    HUTONGWULIU("hutongwuliu", "户通物流"),
    HYESHIP("hyeship", "鸿远物流"),
    HYK("hyk", "上海昊宏国际货物"),
    HZPL("hzpl", "华航快递"),
    ICELAND("iceland", "冰岛(Iceland Post)"),
    IEXPRESS("iexpress", "iExpress"),
    ILOGEN("ilogen", "logen路坚"),
    ILYANG("ilyang", "ILYANG"),
    IMLB2C("imlb2c", "艾姆勒"),
    INDIA("india", "印度(India Post)"),
    INDONESIA("indonesia", "印度尼西亚EMS(Pos Indonesia-EMS)"),
    INPOSDOM("inposdom", "多米尼加（INPOSDOM – Instituto Postal Dominicano）"),
    INTERLINK("interlink", "Interlink Express"),
    IRAN("iran", "伊朗（Iran Post）"),
    ISRAELPOST("israelpost", "以色列(Israel Post)"),
    ITALYSAD("italysad", "Italy SDA"),
    JDEXPRESSUSA("jdexpressusa", "骏达快递"),
    JDIEX("jdiex", "JDIEX"),
    JDPPLUS("jdpplus", "急递"),
    JERSEYPOST("jerseypost", "泽西岛"),
    JETEXPRESSGROUP("jetexpressgroup", "澳速通国际速递"),
    JIACHENEXPRESS("jiachenexpress", "佳辰国际速递"),
    JIAJIATONG56("jiajiatong56", "佳家通货运"),
    JINCHENGWULIU("jinchengwuliu", "锦程物流"),
    JINTONGKD("jintongkd", "劲通快递"),
    JINYUEKUAIDI("jinyuekuaidi", "晋越快递"),
    JISU("jisu", "冀速物流"),
    JIUGONG("jiugong", "九宫物流"),
    JIUYICN("jiuyicn", "久易快递"),
    JIXIANGYOUAU("jixiangyouau", "吉祥邮（澳洲）"),
    JJX888("jjx888", "佳捷翔物流"),
    JORDAN("jordan", "约旦(Jordan Post)"),
    JSEXPRESS("jsexpress", "骏绅物流"),
    JUWU("juwu", "聚物物流"),
    JUZHONGDA("juzhongda", "聚中大"),
    KFWNET("kfwnet", "快服务"),
    KHZTO("khzto", "柬埔寨中通"),
    KOALI("koali", "番薯国际货运"),
    KOREAPOSTKR("koreapostkr", "韩国邮政韩文"),
    KRTAO("krtao", "淘韩国际快递"),
    KSUDI("ksudi", "快速递"),
    KUAIDAWULIU("kuaidawuliu", "快达物流"),
    KUAITAO("kuaitao", "快淘快递"),
    KUAIYOUDA("kuaiyouda", "四川快优达速递"),
    KXDA("kxda", "凯信达"),
    KYRGYZPOST("kyrgyzpost", "吉尔吉斯斯坦(Kyrgyz Post)"),
    KYUE("kyue", "跨跃国际"),
    LANBIAOKUAIDI("lanbiaokuaidi", "蓝镖快递"),
    LANDMARKGLOBAL("landmarkglobal", "Landmark Global"),
    LANHUKUAIDI("lanhukuaidi", "蓝弧快递"),
    LAO("lao", "老挝(Lao Express)"),
    LAPOSTE("laposte", "塞内加尔"),
    LASY56("lasy56", "林安物流"),
    LATVIA("latvia", "拉脱维亚(Latvijas Pasts)"),
    LBBK("lbbk", "立白宝凯物流"),
    LDXPRES("ldxpres", "林道国际快递-英文"),
    LEDAOWULIU("ledaowuliu", "楽道物流"),
    LEDII("ledii", "乐递供应链"),
    LEOPARD("leopard", "云豹国际货运"),
    LETSEML("letseml", "美联快递"),
    LGS("lgs", "lazada"),
    LIANYUN("lianyun", "联运快递"),
    LIBANPOST("libanpost", "黎巴嫩(Liban Post)"),
    LINEX("linex", "Linex"),
    LISHI("lishi", "丽狮物流"),
    LMFEX("lmfex", "良藤国际速递"),
    LOGISTICS("logistics", "華信物流WTO"),
    LONGCPS("longcps", "加拿大龙行速运"),
    LQHT("lqht", "恒通快递"),
    LTEXP("ltexp", "乐天速递"),
    LTPARCEL("ltparcel", "联通快递"),
    LUNDAO("lundao", "论道国际物流"),
    LUTONG("lutong", "鲁通快运"),
    LUXEMBOURG("luxembourg", "卢森堡(Luxembourg Post)"),
    LWE("lwe", "LWE"),
    MACEDONIA("macedonia", "马其顿(Macedonian Post)"),
    MAILIKUAIDI("mailikuaidi", "麦力快递"),
    MAILONGDY("mailongdy", "迈隆递运"),
    MALDIVES("maldives", "马尔代夫(Maldives Post)"),
    MALTA("malta", "马耳他（Malta Post）"),
    MANGGUO("mangguo", "芒果速递"),
    MAPLEEXPRESS("mapleexpress", "今枫国际快运"),
    MAURITIUS("mauritius", "毛里求斯(Mauritius Post)"),
    MEIBANG("meibang", "美邦国际快递"),
    MEIDAEXPRESS("meidaexpress", "美达快递"),
    MEITAI("meitai", "美泰物流"),
    MEXICO("mexico", "墨西哥（Correos de Mexico）"),
    MEXICODENDA("mexicodenda", "Mexico Senda Express"),
    MILKYWAY("milkyway", "银河物流"),
    MJEXP("mjexp", "美龙快递"),
    MONGOLPOST("mongolpost", "蒙古国(Mongol Post)"),
    MOROCCO("morocco", "摩洛哥 ( Morocco Post )"),
    MRW("mrw", "MRW"),
    MULTIPACK("multipack", "Mexico Multipack"),
    MXE56("mxe56", "中俄速通（淼信）"),
    NALEXPRESS("nalexpress", "新亚物流"),
    NEDAHM("nedahm", "红马速递"),
    NEPALPOST("nepalpost", "尼泊尔（Nepal Postal Services）"),
    NEWGISTICS("newgistics", "Newgistics"),
    NIGERIANPOST("nigerianpost", "尼日利亚(Nigerian Postal)"),
    NIUZAIEXPRESS("niuzaiexpress", "牛仔速运"),
    NJHAOBO("njhaobo", "浩博物流"),
    NLE("nle", "NLE"),
    NMHUAHE("nmhuahe", "华赫物流"),
    NNTENGDA("nntengda", "腾达速递"),
    NOVAPOSHTA("novaposhta", "Nova Poshta"),
    NUOER("nuoer", "诺尔国际物流"),
    NUOYAAO("nuoyaao", "偌亚奥国际快递"),
    OMAN("oman", "阿曼(Oman Post)"),
    OMNIVA("omniva", "爱沙尼亚(Eesti Post)"),
    ONWAY("onway", "昂威物流"),
    OPEK("opek", "OPEK"),
    OVERSEAEX("overseaex", "波音速递"),
    PARAGUAY("paraguay", "巴拉圭(Correo Paraguayo)"),
    PDSTOW("pdstow", "全球速递"),
    PEEX("peex", "派尔快递"),
    PEIXINGWULIU("peixingwuliu", "陪行物流"),
    PENGYUANEXPRESS("pengyuanexpress", "鹏远国际速递"),
    PERU("peru", "秘鲁(SERPOST)"),
    PHLPOST("phlpost", "菲律宾（Philippine Postal）"),
    PINDUODUOORDER("pinduoduoorder", "拼多多订单"),
    PINSUXINDA("pinsuxinda", "品速心达快递"),
    PINXINKUAIDI("pinxinkuaidi", "品信快递"),
    PIONEER("pioneer", "先锋国际快递"),
    POLARISEXPRESS("polarisexpress", "北极星快运"),
    PORTUGALCTT("portugalctt", "葡萄牙（Portugal CTT）"),
    PORTUGALSEUR("portugalseur", "Portugal Seur"),
    POSTDANMARKEN("postdanmarken", "丹麦(Post Denmark)"),
    POSTELBE("postelbe", "PostElbe"),
    POSTENAB("postenab", "PostNord(Posten AB)"),
    POSTENNORGE("postennorge", "挪威（Posten Norge）"),
    PTT("ptt", "土耳其"),
    PZHJST("pzhjst", "急顺通"),
    QDANTS("qdants", "ANTS EXPRESS"),
    QESD("qesd", "7E速递"),
    QHXYKD("qhxykd", "雪域快递"),
    QHXYYG("qhxyyg", "雪域易购"),
    QSKDYXGS("qskdyxgs", "千顺快递"),
    QUANTIUM("quantium", "Quantium"),
    QUANTWL("quantwl", "全通快运"),
    QUANXINTONG("quanxintong", "全信通快递"),
    QZX56("qzx56", "全之鑫物流"),
    REDEXPRESS("redexpress", "Red Express"),
    REPUBLIC("republic", "叙利亚(Syrian Post)"),
    RHTEXPRESS("rhtexpress", "睿和泰速运"),
    ROKIN("rokin", "荣庆物流"),
    ROMANIAN("romanian", "罗马尼亚（Posta Romanian）"),
    RRTHK("rrthk", "日日通国际"),
    RWANDA("rwanda", "卢旺达(Rwanda i-posita)"),
    S2C("s2c", "S2C"),
    SAFEXPRESS("safexpress", "Safexpress"),
    SAMOA("samoa", "萨摩亚(Samoa Post)"),
    SAUDIPOST("saudipost", "沙特阿拉伯(Saudi Post)"),
    SCXINGCHENG("scxingcheng", "四川星程快递"),
    SELEKTVRACHT("selektvracht", "Selektvracht"),
    SERBIA("serbia", "塞尔维亚(PE Post of Serbia)"),
    SEUR("seur", "International Seur"),
    SFAU("sfau", "澳丰速递"),
    SFPOST("sfpost", "曹操到"),
    SHANDA56("shanda56", "衫达快运"),
    SHANGHAIKUAITONG("shanghaikuaitong", "上海快通"),
    SHANGHAIWUJIANGMMB("shanghaiwujiangmmb", "上海无疆for买卖宝"),
    SHANGTUGUOJI("shangtuguoji", "尚途国际货运"),
    SHAOKE("shaoke", "捎客物流"),
    SHD56("shd56", "商海德物流"),
    SHENGTONGSCM("shengtongscm", "盛通快递"),
    SHENMA("shenma", "神马快递"),
    SHININGEXPRESS("shiningexpress", "阳光快递"),
    SHIPBYACE("shipbyace", "王牌快递"),
    SHIPSOHO("shipsoho", "苏豪快递"),
    SHIYUNKUAIDI("shiyunkuaidi", "世运快递"),
    SHLEXP("shlexp", "SHL畅灵国际物流"),
    SIHAIET("sihaiet", "四海快递"),
    SIHIEXPRESS("sihiexpress", "四海捷运"),
    SINOEX("sinoex", "中外运速递-中文"),
    SIODEMKA("siodemka", "Siodemka"),
    SIXROAD("sixroad", "易普递"),
    SKYNET("skynet", "skynet"),
    SKYNETWORLDWIDE("skynetworldwide", "skynetworldwide"),
    SKYPOST("skypost", "荷兰Sky Post"),
    SLOVAK("slovak", "斯洛伐克(Slovenská Posta)"),
    SLPOST("slpost", "斯里兰卡(Sri Lanka Post)"),
    SOFAST56("sofast56", "嗖一下同城快递"),
    SPEEDA("speeda", "行必达"),
    SPEEDOEX("speedoex", "申必达"),
    STAKY("staky", "首通快运"),
    STAREX("starex", "星速递"),
    STARYVR("staryvr", "星运快递"),
    SUBAOEX("subaoex", "速豹"),
    SUCHENG("sucheng", "速呈宅配"),
    SUDAPOST("sudapost", "苏丹（Sudapost）"),
    SUFENGKUAIDI("sufengkuaidi", "速风快递"),
    SUIJIAWULIU("suijiawuliu", "穗佳物流"),
    SUPEROZ("superoz", "速配欧翼"),
    SUPINEXPRESS("supinexpress", "速品快递"),
    SWISSPOSTCN("swisspostcn", "瑞士邮政"),
    SZDPEX("szdpex", "深圳DPEX"),
    SZSHIHUATONG56("szshihuatong56", "世华通物流"),
    TAIMEK("taimek", "天美快递"),
    TANZANIA("tanzania", "坦桑尼亚(Tanzania Posts)"),
    TCIXPS("tcixps", "TCI XPS"),
    TDCARGO("tdcargo", "TD Cargo"),
    THUNDEREXPRESS("thunderexpress", "加拿大雷霆快递"),
    TIANXIANG("tianxiang", "天翔快递"),
    TIMEDG("timedg", "万家通快递"),
    TLKY("tlky", "天联快运"),
    TMG("tmg", "株式会社T.M.G"),
    TNTITALY("tntitaly", "TNT Italy"),
    TNTPOSTCN("tntpostcn", "TNT Post"),
    TNY("tny", "TNY物流"),
    TOLLPRIORITY("tollpriority", "Toll Priority(Toll Online)"),
    TOPSHEY("topshey", "顶世国际物流"),
    TUNISIA("tunisia", "突尼斯EMS(Rapid-Poste)"),
    UEX("uex", "UEX国际物流"),
    UGANDA("uganda", "乌干达(Posta Uganda)"),
    UGOEXPRESS("ugoexpress", "邮鸽速运"),
    UKRAINE("ukraine", "乌克兰小包、大包(UkrPoshta)"),
    UKRPOST("ukrpost", "乌克兰小包、大包(UkrPost)"),
    UPSMAILINNO("upsmailinno", "UPS Mail Innovations"),
    USCHUAXIA("uschuaxia", "华夏国际速递"),
    UTAOSCM("utaoscm", "UTAO优到"),
    VANUATU("vanuatu", "瓦努阿图(Vanuatu Post)"),
    VIETNAM("vietnam", "越南小包(Vietnam Posts)"),
    VIPEXPRESS("vipexpress", "鹰运国际速递"),
    WANBOEX("wanboex", "万博快递"),
    WANJIATONG("wanjiatong", "宁夏万家通"),
    WDM("wdm", "万达美"),
    WEXPRESS("wexpress", "威速递"),
    WHGJKD("whgjkd", "香港伟豪国际物流"),
    WINIT("winit", "万邑通"),
    WOTU("wotu", "渥途国际速运"),
    WOWVIP("wowvip", "沃埃家"),
    WTDEX("wtdex", "WTD海外通"),
    WUYUANSUDI("wuyuansudi", "伍圆速递"),
    WYGJ168("wygj168", "万运国际快递"),
    WZHAUNYUN("wzhaunyun", "微转运"),
    XDSHIPPING("xdshipping", "国晶物流"),
    XIANCHENGLIANSUDI("xianchengliansudi", "西安城联速递"),
    XIANGTENG("xiangteng", "翔腾物流"),
    XILAIKD("xilaikd", "西安喜来快递"),
    XINGYUANKUAIDI("xingyuankuaidi", "新元快递"),
    XINNING("xinning", "新宁物流"),
    XIPOST("xipost", "西邮寄"),
    XTB("xtb", "鑫通宝物流"),
    XYD666("xyd666", "鑫远东速运"),
    YAMAXUNWULIU("yamaxunwuliu", "亚马逊中国"),
    YATFAI("yatfai", "一辉物流"),
    YCGGLOBAL("ycgglobal", "YCG物流"),
    YIBANGWULIU("yibangwuliu", "一邦速递"),
    YIDIHUI("yidihui", "驿递汇速递"),
    YIHANGMALL("yihangmall", "易航物流"),
    YILINGSUYUN("yilingsuyun", "亿领速运"),
    YIQIGUOJIWULIU("yiqiguojiwuliu", "一柒国际物流"),
    YISHUNHANG("yishunhang", "亿顺航"),
    YISONG("yisong", "宜送"),
    YITONGDA("yitongda", "易通达"),
    YIYOU("yiyou", "易邮速运"),
    YJHGO("yjhgo", "武汉优进汇"),
    YKOUAN("ykouan", "洋口岸"),
    YONGBANGWULIU("yongbangwuliu", "永邦国际物流"),
    YOUJIA("youjia", "友家速递"),
    YOURSCM("yourscm", "雅澳物流"),
    YUANDUN("yuandun", "远盾物流"),
    YUJTONG("yujtong", "宇捷通"),
    YWEXPRESS("ywexpress", "远为快递"),
    ZENZEN("zenzen", "三三国际物流"),
    ZHITENGWULIU("zhitengwuliu", "志腾物流"),
    ZHUOSHIKUAIYUN("zhuoshikuaiyun", "卓实快运"),
    ZY100("zy100", "中远快运"),
    ZYZOOM("zyzoom", "增速跨境");

    private String key;
    private String value;

    public static String getValue(String key) {
        ExpressEnum[] expressEnums = values();
        for (ExpressEnum expressEnum : expressEnums) {
            if (expressEnum.key().equals(key)) {
                return expressEnum.value();
            }
        }
        return null;
    }

    public String key() {
        return key;
    }

    public String value() {
        return value;
    }

    ExpressEnum(String key, String value) {
        this.key = key;
        this.value = value;
    }
}
