
spring:
  application:
    name: ycandyz-master-controller
  profiles:
    active: test

logging:
  config: classpath:logback-spring.xml

after-sales-days: 7

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0