server:
  port: 8002
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://youchuan-prod-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: datav
    password: eovkug3821GyXgKB
  redis:
    host: youchuan-prod-redis-1.5fqnep.ng.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 3
    password: 1MVFIWVUS!@VX%qx

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥

exclude:
  path: /login,/error,/swagger-ui.html

#快递100相关参数
kuaidi:
  autonumber:
    url: http://www.kuaidi100.com/autonumber/auto?num=NUM&key=KEY
  poll:
    url: https://poll.kuaidi100.com/poll
    callback: https://api-manage.ycandyz.com/uke/j/youchuan-master/mall/order/shipment/callback
  key: RGUCsfJZ9794
  customer: FDED135A3EEE3F24749F3FB244D0A03B
  secret: 0aa5dd906ba7404db4ac569ca8da20a6
  userid: 7edbc3841b3a4bb9b4443d4a2ee654ff
