server:
  port: 8003
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://youchuan-test-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: project_dev
    password: p3BjALdQI4SjH0w5
  redis:
    host: youchuan-test-redis.5fqnep.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 3

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
    # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥
