server:
  port: 9002
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    #url: jdbc:mysql://youchuan-prod-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    #username: project_test
    #password: pxEQg*ow
    name: yc-test
    url: jdbc:mysql://youchuan-test-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: project
    password: lKURYZ7HQq8k4rCC
  redis:
    host: youchuan-test-redis.5fqnep.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 1

mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycandyz.master.domain.entity.*
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥

logging:
  level:
    com.ycandyz.master.dao: debug

ignored:
  urls:
    - /
    - /login
    - /error
    - /mall/order/shipment/callback
    - /mallBuyer/shipment/callback

#快递100相关参数
kuaidi:
  autonumber:
    url: http://www.kuaidi100.com/autonumber/auto?num=NUM&key=KEY
  poll:
    url: https://poll.kuaidi100.com/poll
    callback: https://test-api-manage.ycandyz.com/youchuan-master/mall/order/shipment/callback
  key: RGUCsfJZ9794
  customer: FDED135A3EEE3F24749F3FB244D0A03B
  secret: 0aa5dd906ba7404db4ac569ca8da20a6
  userid: 7edbc3841b3a4bb9b4443d4a2ee654ff
