server:
  port: 9001
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    name: yc-dev
    url: jdbc:mysql://youchuan-test-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc-dev?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 9HzyhWj6Gcnijbki
  redis:
    host: youchuan-test-redis.5fqnep.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 3

mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycandyz.master.domain.entities.*
    # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥
sign:
  authConfigSecret: b1f5d2f3f9f818c1a2c03da10c81e542          #验签密钥

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.ycandyz.master.dao: debug

ignored:
  urls:
    - /
    - /login
    - /error
    - /mall/order/shipment/callback
    - /mall-buyer-shipping/mallBuyer/shipment/callback

DEFAULT_TOKEN: eyJhZ2VudF9pZCI6ICIwIiwgImVtcGxveWVlX2lkIjogMzk0LCAiZW52IjogImRldiIsICJleHAiOiAxNjAyNzYyNzAxLCAiaWF0IjogMTYwMjc1NTUwMSwgImlzX2Jvc3MiOiAxLCAib3JnYW5pemVfaWQiOiAiNDQ4IiwgInBsYXRmb3JtIjogNSwgInJvbGUiOiAiMCIsICJzaG9wX25vIjogImJlaXF1YW5fc3RvcmUiLCAidXNlcl9pZCI6ICIxMDQwMSIsICJ3eG1pbmlfb3Blbl9pZCI6ICIiLCAianRpIjogIjkzZWU5NWFjMzdiZjBmZTE2MjRhZmE2N2FiODI5OWQ0In0

#快递100相关参数
kuaidi:
  autonumber:
    url: http://www.kuaidi100.com/autonumber/auto?num=NUM&key=KEY
  poll:
    url: https://poll.kuaidi100.com/poll
    callback: https://dev-api-manage.ycandyz.com/youchuan-master/mall/order/shipment/callback
  key: RGUCsfJZ9794
  customer: FDED135A3EEE3F24749F3FB244D0A03B
  secret: 0aa5dd906ba7404db4ac569ca8da20a6
  userid: 7edbc3841b3a4bb9b4443d4a2ee654ff

#每个sheet条数
excel:
  sheet: 50