server:
  port: 9003
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    name: yc
    url: jdbc:mysql://youchuan-uat-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: project_uat
    password: LL0Nq6BWuYZRLrHY
  redis:
    host: youchuan-uat-redis-1.5fqnep.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 0

mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycandyz.master.domain.entity.*

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥
sign:
  authConfigSecret: b1f5d2f3f9f818c1a2c03da10c81e542          #验签密钥

logging:
  level:
    com.ycandyz.master.dao: debug

ignored:
  urls:
    - /
    - /login
    - /error
    - /mall/order/shipment/callback
    - /mall-buyer-shipping/mallBuyer/shipment/callback
    - /**/订单.xls

#快递100相关参数
kuaidi:
  autonumber:
    url: http://www.kuaidi100.com/autonumber/auto?num=NUM&key=KEY
  poll:
    url: https://poll.kuaidi100.com/poll
    callback: https://uat-api-manage.ycandyz.com/youchuan-master/mall/order/shipment/callback
  key: RGUCsfJZ9794
  customer: FDED135A3EEE3F24749F3FB244D0A03B
  secret: 0aa5dd906ba7404db4ac569ca8da20a6
  userid: 7edbc3841b3a4bb9b4443d4a2ee654ff


#每个sheet条数
excel:
  sheet: 5000

s3:
  downFileUrlPefix: https://uat-file.ycandyz.com/
  bucketName: uat-pan.ycandyz.com
  accessKey: AKIAVEJEAKGYZUSB2HUG
  secretKey: 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
  keyPefix: xls/