server:
  port: 9001
  servlet:
    context-path: /youchuan-master

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://youchuan-test-rds.c1eouiepocc7.rds.cn-north-1.amazonaws.com.cn:3306/yc-dev?serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 9HzyhWj6Gcnijbki
    type: com.zaxxer.hikari.HikariDataSource           # 当前数据源操作类型
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: ukeHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: youchuan-test-redis.5fqnep.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
    database: 3
  kafka:
    bootstrap-servers: kafka-dev.ycandyz.com:9092
    producer:
      #发生错误消息重发次数
      retries: 3
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false

mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycandyz.master.domain.entities.*
    # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  authConfigSecret: c1f5d2f3f9f818c1a2c03da10c81e542          #token密钥
sign:
  authConfigSecret: b1f5d2f3f9f818c1a2c03da10c81e542          #验签密钥

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.ycandyz.master.dao: debug

ignored:
  urls:
    - /
    - /login
    - /error
    - /mall/order/shipment/callback
    - /mall-buyer-shipping/mallBuyer/shipment/callback
    - /**/订单.xls
    - /base-bank/**
    - /kafka/**/**

DEFAULT_TOKEN: eyJhZ2VudF9pZCI6ICIwIiwgImVtcGxveWVlX2lkIjogMzk0LCAiZW52IjogImRldiIsICJleHAiOiAxNjAyNzYyNzAxLCAiaWF0IjogMTYwMjc1NTUwMSwgImlzX2Jvc3MiOiAxLCAib3JnYW5pemVfaWQiOiAiNDQ4IiwgInBsYXRmb3JtIjogNSwgInJvbGUiOiAiMCIsICJzaG9wX25vIjogImJlaXF1YW5fc3RvcmUiLCAidXNlcl9pZCI6ICIxMDQwMSIsICJ3eG1pbmlfb3Blbl9pZCI6ICIiLCAianRpIjogIjkzZWU5NWFjMzdiZjBmZTE2MjRhZmE2N2FiODI5OWQ0In0

#快递100相关参数
kuaidi:
  autonumber:
    url: http://www.kuaidi100.com/autonumber/auto?num=NUM&key=KEY
  poll:
    url: https://poll.kuaidi100.com/poll
    callback: https://dev-api-manage.ycandyz.com/youchuan-master/mall/order/shipment/callback
  key: RGUCsfJZ9794
  customer: FDED135A3EEE3F24749F3FB244D0A03B
  secret: 0aa5dd906ba7404db4ac569ca8da20a6
  userid: 7edbc3841b3a4bb9b4443d4a2ee654ff

#每个sheet条数
excel:
  sheet: 5000

s3:
  downFileUrlPefix: https://dev-file.ycandyz.com/
  bucketName: dev-pan.ycandyz.com
  accessKey: AKIAVEJEAKGYZUSB2HUG
  secretKey: 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
  keyPefix: xls/

#阿里云发送消息配置
aliyun:
  access:
    keyId: LTAI4G38fpzXvwLpSUms4YNU
    secret: qMYb4yRyoz4yMxtUBIA8cdSK1GTTGW
    region: cn-beijing
  sms:
    domain: dysmsapi.aliyuncs.com
    product: Dysmsapi
    sign: 有传科技4
    template_code: SMS_203190683
    #有传客服电话
    service-number: 13714366094